import { useState, useRef, useEffect, useCallback } from 'react';
import { Email, Tone, Length } from '@/lib/types';
import { useSendReply, useGenerateDraft, useJob, useDrafts } from '@/lib/api/hooks';
import { useModKey } from '@/lib/hooks/useOS';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { JobStatus } from '@/components/ui/badges';
import { Skeleton } from '@/components/ui/skeletons';
import { toast } from 'sonner';
import {
  Send,
  Sparkles,
  Loader2,
  RefreshCw,
} from 'lucide-react';
import { motion } from 'framer-motion';

interface ReplyComposerProps {
  email: Email;
  onSent: () => void;
}

const tones: Tone[] = ['Professional', 'Friendly', 'Short', 'Firm', 'Apologetic'];
const lengths: Length[] = ['Short', 'Medium', 'Detailed'];

export function ReplyComposer({ email, onSent }: ReplyComposerProps) {
  const [content, setContent] = useState('');
  const [selectedTone, setSelectedTone] = useState<Tone>('Professional');
  const [selectedLength, setSelectedLength] = useState<Length>('Medium');
  const [jobId, setJobId] = useState<string | null>(null);
  const [userEdited, setUserEdited] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const autoGeneratedForEmailRef = useRef<string | null>(null);
  const modKey = useModKey();

  const sendReply = useSendReply();
  const generateDraft = useGenerateDraft();
  const { data: job } = useJob(jobId);
  const { data: drafts, isLoading: draftsLoading, refetch: refetchDrafts } = useDrafts(email.id);
  const latestDraft = drafts?.[0];

  const autoResize = useCallback(() => {
    const ta = textareaRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = `${Math.max(220, ta.scrollHeight)}px`;
  }, []);

  useEffect(() => {
    autoResize();
  }, [content, autoResize]);

  useEffect(() => {
    setContent('');
    setUserEdited(false);
    setJobId(null);
    autoGeneratedForEmailRef.current = null;
  }, [email.id]);

  useEffect(() => {
    if (!latestDraft) return;
    setSelectedTone(latestDraft.tone);
    setSelectedLength(latestDraft.length);
    setContent((current) => (userEdited && current ? current : latestDraft.content));
  }, [latestDraft, userEdited]);

  const handleGenerate = useCallback(async (silent = false) => {
    try {
      const result = await generateDraft.mutateAsync({
        emailId: email.id,
        request: {
          tone: selectedTone,
          length: selectedLength,
          emailFrom: email.fromName,
          emailSubject: email.subject,
          emailBody: email.bodyText,
        },
      });
      setJobId(result.jobId);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to start AI generation';
      if (!silent) {
        toast.error(message);
      }
    }
  }, [email.bodyText, email.fromName, email.id, email.subject, generateDraft, selectedLength, selectedTone]);

  useEffect(() => {
    if (draftsLoading || latestDraft || jobId || autoGeneratedForEmailRef.current === email.id) {
      return;
    }

    autoGeneratedForEmailRef.current = email.id;
    void handleGenerate(true);
  }, [draftsLoading, latestDraft, jobId, email.id, handleGenerate]);

  useEffect(() => {
    if (job?.status === 'done') {
      refetchDrafts().then(({ data }) => {
        if (data && data.length > 0) {
          setContent(data[0].content);
          setSelectedTone(data[0].tone);
          setSelectedLength(data[0].length);
          setUserEdited(false);
        }
      });
      setJobId(null);
      toast.success('AI draft is ready below the email.');
    } else if (job?.status === 'failed') {
      toast.error(job.error ? `Draft generation failed: ${job.error}` : 'Draft generation failed');
      setJobId(null);
    }
  }, [job?.error, job?.status, refetchDrafts]);

  const handleSend = async () => {
    if (!content.trim() || sendReply.isPending) return;
    try {
      await sendReply.mutateAsync({
        emailId: email.id,
        body: content.trim(),
        draftId: latestDraft?.id,
      });
      toast.success('Reply sent!');
      setContent('');
      setUserEdited(false);
      onSent();
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to send reply';
      toast.error(message);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
      e.preventDefault();
      void handleSend();
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: [0.4, 0, 0.2, 1] }}
      className="border-t border-border bg-muted/20"
    >
      <div className="p-4 space-y-4">
        <div className="flex items-start justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <div className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10">
                <Sparkles className="h-3.5 w-3.5 text-primary" />
              </div>
              <span className="text-sm font-semibold text-foreground">AI Reply Draft</span>
            </div>
            <p className="text-xs text-muted-foreground">
              This draft is generated for the open email and stays editable before you send it.
            </p>
          </div>
          <div className="text-[11px] text-muted-foreground whitespace-nowrap">
            {modKey}+Enter to send
          </div>
        </div>

        <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]">
          <div>
            <Label className="text-[11px] text-muted-foreground">Tone</Label>
            <Select value={selectedTone} onValueChange={(v) => setSelectedTone(v as Tone)}>
              <SelectTrigger className="mt-1 h-9 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {tones.map((tone) => (
                  <SelectItem key={tone} value={tone}>{tone}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label className="text-[11px] text-muted-foreground">Length</Label>
            <Select value={selectedLength} onValueChange={(v) => setSelectedLength(v as Length)}>
              <SelectTrigger className="mt-1 h-9 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {lengths.map((length) => (
                  <SelectItem key={length} value={length}>{length}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-end">
            <Button
              variant="outline"
              onClick={() => void handleGenerate()}
              disabled={!!jobId}
              className="w-full gap-2 md:w-auto"
            >
              {jobId ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
              Regenerate
            </Button>
          </div>
        </div>

        {jobId && job && (
          <div className="flex items-center gap-2">
            <JobStatus status={job.status as 'queued' | 'processing' | 'done' | 'failed'} />
            <span className="text-xs text-muted-foreground">Generating a fresh draft for this email</span>
          </div>
        )}

        {latestDraft && !jobId && (
          <div className="flex items-center gap-3 text-xs text-muted-foreground">
            <span>Latest AI version</span>
            <span>{latestDraft.tone}</span>
            <span>{latestDraft.length}</span>
          </div>
        )}

        {draftsLoading && !latestDraft ? (
          <div className="space-y-3 rounded-xl border border-border bg-background p-4">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-2/3" />
          </div>
        ) : (
          <textarea
            ref={textareaRef}
            value={content}
            onChange={(e) => {
              setContent(e.target.value);
              setUserEdited(true);
            }}
            onKeyDown={handleKeyDown}
            placeholder={jobId ? 'Generating AI draft...' : 'Your editable reply will appear here.'}
            rows={8}
            className={cn(
              'min-h-[220px] w-full resize-y rounded-xl border border-border bg-background px-4 py-3',
              'text-sm text-foreground placeholder:text-muted-foreground',
              'focus:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/30',
              'transition-all duration-150'
            )}
          />
        )}

        <div className="flex items-center justify-between gap-3">
          <div className="text-xs text-muted-foreground">
            Edit the generated reply however you want, then send it from here.
          </div>
          <Button
            onClick={() => void handleSend()}
            disabled={!content.trim() || sendReply.isPending || !!jobId}
            className="gap-2"
          >
            {sendReply.isPending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Sending...
              </>
            ) : (
              <>
                <Send className="h-4 w-4" />
                Send Reply
              </>
            )}
          </Button>
        </div>
      </div>
    </motion.div>
  );
}
